### PR TITLE
Rails 6 compatibility 

### PR DESCRIPTION
**Pull request by joevandyk**

### CODE REVIEW

**Comment by Envek** [comment]
It looks like failing test is related to [Lazy transactions](https://github.com/rails/rails/pull/32647) feature. 

See how developers of the Isolator gem worked around it: https://github.com/palkan/isolator/pull/20/files#diff-85a7e76d12511ed333927e4fd2b8da1d

**Comment by Envek** [comment]
I will merge your PR and fix Travis builds after few hours. You did all the job for me, thank you!

**Comment by joevandyk** [comment]
Thanks!

Any chance you could release a new version?

**Comment by Envek** [comment]
Already released, sorry for the delay! Please grab v0.1.4 from Rubygems.

**Pull request merged**
